### ISSUE TITLE
下载完图片后一张一张加载进去，这样让我每次刷同样的数据但每张图片顺序都不一样。

### ISSUE THREAD

**Issue by liujingtech** [dodola/android_waterfall#14]
有什么办法可以保持每次加载的图片位置都一样吗。现在是第一次可能a图片在左边，刷新后就到右边去了。

比如提前加载好图片的位置，当图片下载完成后直接在预加载的位置显示图片。

**Comment by dodola** [comment]
现在加载是多线程的加载，如果能按照下载顺序添加就能保证顺序一样，涉及到线程同步等问题
